### ISSUE TITLE
Service Accounts named 'default' are hard to distinguish when using the dashboard UI search

### ISSUE THREAD

**Issue by oguzhan-yilmaz** [turbot/steampipe-mod-kubernetes-insights#62]
**Is your feature request related to a problem? Please describe.**
I can not see which namespace a Service Account belongs to while searching for it on the UI using the 'Kubernetes Service Account Detail' dashboard.
I came across this issue when trying to find the default Service Account for a namespace.

**Describe the solution you'd like**
Search shows some additional context like which cluster it's in, and I'd like it to have the namespace info too.

**Additional context**

Here's a screenshot of searching for the default namespace:
![Image](https://github.com/user-attachments/assets/c62bc4da-95fc-46db-8cc5-4fbbf94eadb0)

The related code, I think, can be found here:
<https://github.com/turbot/steampipe-mod-kubernetes-insights/blob/91c5d24b4b480af75ca4d97790f2a062fec5103c/dashboards/serviceaccount/service_account_detail.sp#L182-L195>

**Comment by khushboo9024** [comment]
@oguzhan-yilmaz Apologies for the inconvenience.
We have raised a [PR](https://github.com/turbot/steampipe-mod-kubernetes-insights/pull/65) in which we added `namespace` to the service account title for unique identification.
Please let us know if this works for you.

Thanks.

**Comment by oguzhan-yilmaz** [comment]
Hey @khushboo9024, I think it'd be better to add the namespace info as a tag like the cluster-name.

And it could be added to other dashboards as well. Thank you!

**Comment by khushboo9024** [comment]
@oguzhan-yilmaz  We have updated the [PR](https://github.com/turbot/steampipe-mod-kubernetes-insights/pull/65) with `namespace` info as a tag to the service account detail page for unique identification . Please let us know if this works for you.



Thanks

**Comment by oguzhan-yilmaz** [comment]
Thank you this is what I've been looking for!
